In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

Шаг № 1 блока «4.4 Задача классификации. Деревья решений»

Для данного датасета обучите дерево решений (для обучения используйте массивы с ключами x, y), затем предскажите классы для данных доступных в файле по ключу x_test.

В качестве ответа запишите метку класса - 1 или 0

In [2]:
train_data = np.load('train_data.npz')
print(train_data.files)

['x', 'y', 'x_test']


Первый вариант:

In [3]:
x = train_data['x']
y = train_data['y']
x_test = train_data['x_test']

tree_clf = tree.DecisionTreeClassifier()
tree_clf.fit(x, y)

y_pred = tree_clf.predict(x_test)

print(y_pred)

[1 1 0 1 1 0 1 1 1 1]


Второй вариант:

In [4]:
# Создаем объекты `DataFrame` для дальнейшей работы с данными (чтобы рассчитать корреляцию входных данных друг с другом)
x = pd.DataFrame(train_data["x"])
y = pd.DataFrame(train_data["y"])
x_test = pd.DataFrame(train_data["x_test"])

In [5]:
# Выводим коэффициенты корреляции x
corr_matrix_1 = x.corr()
corr_matrix_1

0         1         2         3         4         5         6   \
0   1.000000  0.322627  0.997829  0.987199  0.171614  0.505969  0.676417   
1   0.322627  1.000000  0.328476  0.320141 -0.026114  0.234023  0.301501   
2   0.997829  0.328476  1.000000  0.986302  0.208552  0.557113  0.716045   
3   0.987199  0.320141  0.986302  1.000000  0.177417  0.497818  0.685142   
4   0.171614 -0.026114  0.208552  0.177417  1.000000  0.661211  0.524459   
5   0.505969  0.234023  0.557113  0.497818  0.661211  1.000000  0.883378   
6   0.676417  0.301501  0.716045  0.685142  0.524459  0.883378  1.000000   
7   0.821267  0.289397  0.850066  0.821684  0.556422  0.832620  0.922518   
8   0.148196  0.068177  0.183886  0.151497  0.558328  0.606053  0.504099   
9  -0.306803 -0.072682 -0.256174 -0.278594  0.590406  0.570369  0.342093   
10  0.675832  0.270477  0.688606  0.729932  0.302048  0.495168  0.629259   
11 -0.099063  0.381449 -0.088485 -0.068050  0.063734  0.042582  0.073098   
12  0.671440  0.276250  0.690539  0.724513  0.297708  0.546672  0.657805   
13  0.733605  0.256683  0.742759  0.798452  0.246385  0.453499  0.615038   
14 -0.228858  0.004429 -0.208896 -0.173045  0.329672  0.133516  0.094134   
15  0.214552  0.192102  0.259793  0.220356  0.327875  0.745187  0.677162   
16  0.198026  0.144184  0.232033  0.210846  0.254240  0.571373  0.693959   
17  0.373446  0.157870  0.404727  0.368779  0.384261  0.640949  0.680941   
18 -0.106408 -0.001112 -0.083372 -0.074587  0.197623  0.230603  0.179260   
19 -0.035609  0.058903  0.002040 -0.013636  0.293914  0.515341  0.456174   
20  0.969276  0.350236  0.969214  0.962428  0.214690  0.534895  0.687593   
21  0.297877  0.911152  0.304026  0.288347  0.034208  0.246982  0.300150   
22  0.965073  0.355993  0.970362  0.958998  0.241128  0.590031  0.729152   
23  0.940701  0.341503  0.941142  0.959030  0.207303  0.508608  0.674828   
24  0.120767  0.075502  0.151847  0.124006  0.804387  0.567391  0.450257   
25  0.419266  0.277592  0.461848  0.395694  0.478543  0.868722  0.759507   
26  0.530766  0.301611  0.567882  0.515872  0.440566  0.817617  0.886676   
27  0.744094  0.290986  0.771300  0.721273  0.505658  0.815422  0.861044   
28  0.166349  0.099576  0.191815  0.145663  0.394608  0.513471  0.413799   
29  0.016050  0.125577  0.060320  0.012111  0.509062  0.693617  0.522324   

          7         8         9   ...        20        21        22        23  \
0   0.821267  0.148196 -0.306803  ...  0.969276  0.297877  0.965073  0.940701   
1   0.289397  0.068177 -0.072682  ...  0.350236  0.911152  0.355993  0.341503   
2   0.850066  0.183886 -0.256174  ...  0.969214  0.304026  0.970362  0.941142   
3   0.821684  0.151497 -0.278594  ...  0.962428  0.288347  0.958998  0.959030   
4   0.556422  0.558328  0.590406  ...  0.214690  0.034208  0.241128  0.207303   
5   0.832620  0.606053  0.570369  ...  0.534895  0.246982  0.590031  0.508608   
6   0.922518  0.504099  0.342093  ...  0.687593  0.300150  0.729152  0.674828   
7   1.000000  0.466011  0.175314  ...  0.829060  0.290557  0.855462  0.808137   
8   0.466011  1.000000  0.489212  ...  0.186274  0.087125  0.220413  0.177253   
9   0.175314  0.489212  1.000000  ... -0.248255 -0.047537 -0.199243 -0.227100   
10  0.693720  0.304236  0.005609  ...  0.712283  0.189835  0.717397  0.749529   
11  0.016267  0.125293  0.163155  ... -0.114849  0.403830 -0.104350 -0.085970   
12  0.707186  0.315566  0.045539  ...  0.694555  0.195560  0.718604  0.728866   
13  0.687121  0.223829 -0.085892  ...  0.755218  0.193971  0.759344  0.809775   
14  0.022169  0.186570  0.405297  ... -0.236027 -0.078256 -0.221872 -0.186979   
15  0.500642  0.435906  0.558194  ...  0.211344  0.143298  0.266955  0.205517   
16  0.443641  0.351146  0.443077  ...  0.189806  0.101372  0.229175  0.190972   
17  0.612572  0.399992  0.342944  ...  0.354623  0.080940  0.392145  0.338759   
18  0.092831  0.454768  0.347926  ... -0.130998 -0.088847 -0.105135 -0.112990   
19  0.268246  0.350070  0.687676 

In [6]:
# Выводим коэффициенты корреляции x_test
corr_matrix_2 = x_test.corr()
corr_matrix_2

0         1         2         3         4         5         6   \
0   1.000000  0.395207  0.999220  0.996201  0.137071  0.534528  0.694270   
1   0.395207  1.000000  0.399426  0.381394 -0.011666  0.586623  0.431091   
2   0.999220  0.399426  1.000000  0.997815  0.165025  0.563499  0.719409   
3   0.996201  0.381394  0.997815  1.000000  0.192819  0.568210  0.741958   
4   0.137071 -0.011666  0.165025  0.192819  1.000000  0.630857  0.469384   
5   0.534528  0.586623  0.563499  0.568210  0.630857  1.000000  0.861164   
6   0.694270  0.431091  0.719409  0.741958  0.469384  0.861164  1.000000   
7   0.876601  0.530754  0.890111  0.902416  0.489832  0.804507  0.876377   
8   0.171475  0.296968  0.177197  0.199642  0.388429  0.219340  0.233377   
9  -0.587359 -0.150280 -0.562296 -0.547101  0.491936  0.253981  0.008933   
10  0.863494  0.631586  0.872381  0.885842  0.286984  0.738387  0.858019   
11  0.051418  0.647286  0.066064  0.088994  0.212326  0.516184  0.490260   
12  0.836990  0.700423  0.849074  0.856605  0.247190  0.780885  0.882449   
13  0.938997  0.521504  0.946287  0.958076  0.287959  0.695652  0.850574   
14  0.259168  0.142114  0.284226  0.331666  0.528393  0.578704  0.771900   
15 -0.105571  0.458389 -0.078192 -0.073804  0.162785  0.627795  0.503719   
16  0.024601  0.402120  0.053135  0.070218  0.204691  0.646244  0.663066   
17  0.490682  0.616043  0.513861  0.534471  0.398533  0.847528  0.886720   
18  0.172483  0.610045  0.187436  0.208301  0.357665  0.606005  0.545674   
19 -0.259828  0.125654 -0.232740 -0.212450  0.224505  0.463095  0.411875   
20  0.991772  0.501598  0.991494  0.986970  0.113961  0.572740  0.711309   
21  0.216689  0.963114  0.219872  0.207148 -0.053551  0.452438  0.312380   
22  0.975399  0.516448  0.977844  0.970154  0.103691  0.601493  0.733500   
23  0.992087  0.476326  0.993746  0.993730  0.169983  0.598212  0.749006   
24  0.027048  0.010841  0.057029  0.087572  0.866966  0.520948  0.450972   
25 -0.022374  0.454835  0.001081 -0.023869  0.146151  0.559315  0.300553   
26  0.235392  0.439335  0.263442  0.254016  0.182542  0.676564  0.631549   
27  0.744217  0.660772  0.764312  0.766050  0.476826  0.885771  0.870942   
28  0.005707  0.612506  0.007952 -0.002244  0.189431  0.197037  0.040155   
29 -0.503063 -0.007934 -0.475357 -0.487157  0.228846  0.319653  0.045430   

          7         8         9   ...        20        21        22        23  \
0   0.876601  0.171475 -0.587359  ...  0.991772  0.216689  0.975399  0.992087   
1   0.530754  0.296968 -0.150280  ...  0.501598  0.963114  0.516448  0.476326   
2   0.890111  0.177197 -0.562296  ...  0.991494  0.219872  0.977844  0.993746   
3   0.902416  0.199642 -0.547101  ...  0.986970  0.207148  0.970154  0.993730   
4   0.489832  0.388429  0.491936  ...  0.113961 -0.053551  0.103691  0.169983   
5   0.804507  0.219340  0.253981  ...  0.572740  0.452438  0.601493  0.598212   
6   0.876377  0.233377  0.008933  ...  0.711309  0.312380  0.733500  0.749006   
7   1.000000  0.295436 -0.224935  ...  0.892150  0.389764  0.877566  0.915502   
8   0.295436  1.000000 -0.121476  ...  0.183933  0.347428  0.160484  0.206853   
9  -0.224935 -0.121476  1.000000  ... -0.585368 -0.089510 -0.585805 -0.551814   
10  0.954170  0.284401 -0.285352  ...  0.897631  0.516569  0.873429  0.913093   
11  0.392758  0.264868  0.391056  ...  0.132070  0.718716  0.101827  0.150914   
12  0.933811  0.251906 -0.298687  ...  0.885654  0.587688  0.893848  0.896248   
13  0.965485  0.278431 -0.391044  ...  0.953417  0.380209  0.932911  0.969290   
14  0.576719  0.231599  0.380699  ...  0.263130  0.159315  0.241496  0.322294   
15  0.194599 -0.207747  0.584292  ... -0.033032  0.441855  0.023282 -0.019422   
16  0.317626 -0.050569  0.532270  ...  0.077483  0.391947  0.117858  0.104493   
17  0.778657  0.122595  0.224971  ...  0.542882  0.539197  0.542533  0.572994   
18  0.532631  0.132320  0.400297  ...  0.236185  0.611418  0.192448  0.259902   
19  0.048076 -0.244230  0.767540 

In [7]:
# Входные данные для обучения модели (x) заменяем на те, которые имеют сильную корреляцию друг с другом (коэффициент корреляции больше 0.9). Данные x_test также преобразовываем, чтобы оставить только те, которые имеют максимальную корреляцию друг с другом (коэффициент корреляции больше 0.9).

correlation = 0.9

df = x[x.corr() > correlation].fillna(0)
df_test = x_test[x_test.corr() > correlation].fillna(0)

tree_clf = tree.DecisionTreeClassifier().fit(df, y)
y_pred = tree_clf.predict(df_test)

print(y_pred)

[1 1 0 1 1 1 1 1 0 1]


In [8]:
# Увеличиваем коэффициент корреляции до 0.95

correlation = 0.95

df = x[x.corr() > correlation].fillna(0)
df_test = x_test[x_test.corr() > correlation].fillna(0)

tree_clf = tree.DecisionTreeClassifier().fit(df, y)

y_pred = tree_clf.predict(df_test)

print(y_pred)

[1 1 0 1 1 1 0 1 0 1]
