In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

Шаг № 1 блока «4.4 Задача классификации. Деревья решений»

Для данного датасета обучите дерево решений (для обучения используйте массивы с ключами x, y), затем предскажите классы для данных доступных в файле по ключу x_test.

В качестве ответа запишите метку класса - 1 или 0

In [2]:
train_data = np.load('train_data.npz')
print(train_data.files)

['x', 'y', 'x_test']


Первый вариант:

In [3]:
x = train_data['x']
y = train_data['y']
x_test = train_data['x_test']

tree_clf = tree.DecisionTreeClassifier()
tree_clf.fit(x, y)

y_pred = tree_clf.predict(x_test)

print(y_pred)

[1 1 0 1 1 0 1 1 1 1]


Второй вариант:

In [4]:
# Создаем объекты `DataFrame` для дальнейшей работы с данными (чтобы рассчитать корреляцию входных данных друг с другом)
x = pd.DataFrame(train_data["x"])
y = pd.DataFrame(train_data["y"])
x_test = pd.DataFrame(train_data["x_test"])

In [5]:
# Выводим коэффициенты корреляции x
corr_matrix_1 = x.corr()
print(corr_matrix_1)

          0         1         2         3         4         5         6   \
0   1.000000  0.322627  0.997829  0.987199  0.171614  0.505969  0.676417   
1   0.322627  1.000000  0.328476  0.320141 -0.026114  0.234023  0.301501   
2   0.997829  0.328476  1.000000  0.986302  0.208552  0.557113  0.716045   
3   0.987199  0.320141  0.986302  1.000000  0.177417  0.497818  0.685142   
4   0.171614 -0.026114  0.208552  0.177417  1.000000  0.661211  0.524459   
5   0.505969  0.234023  0.557113  0.497818  0.661211  1.000000  0.883378   
6   0.676417  0.301501  0.716045  0.685142  0.524459  0.883378  1.000000   
7   0.821267  0.289397  0.850066  0.821684  0.556422  0.832620  0.922518   
8   0.148196  0.068177  0.183886  0.151497  0.558328  0.606053  0.504099   
9  -0.306803 -0.072682 -0.256174 -0.278594  0.590406  0.570369  0.342093   
10  0.675832  0.270477  0.688606  0.729932  0.302048  0.495168  0.629259   
11 -0.099063  0.381449 -0.088485 -0.068050  0.063734  0.042582  0.073098   
12  0.671440

In [6]:
# Выводим коэффициенты корреляции x_test
corr_matrix_2 = x_test.corr()
print(corr_matrix_2)

          0         1         2         3         4         5         6   \
0   1.000000  0.395207  0.999220  0.996201  0.137071  0.534528  0.694270   
1   0.395207  1.000000  0.399426  0.381394 -0.011666  0.586623  0.431091   
2   0.999220  0.399426  1.000000  0.997815  0.165025  0.563499  0.719409   
3   0.996201  0.381394  0.997815  1.000000  0.192819  0.568210  0.741958   
4   0.137071 -0.011666  0.165025  0.192819  1.000000  0.630857  0.469384   
5   0.534528  0.586623  0.563499  0.568210  0.630857  1.000000  0.861164   
6   0.694270  0.431091  0.719409  0.741958  0.469384  0.861164  1.000000   
7   0.876601  0.530754  0.890111  0.902416  0.489832  0.804507  0.876377   
8   0.171475  0.296968  0.177197  0.199642  0.388429  0.219340  0.233377   
9  -0.587359 -0.150280 -0.562296 -0.547101  0.491936  0.253981  0.008933   
10  0.863494  0.631586  0.872381  0.885842  0.286984  0.738387  0.858019   
11  0.051418  0.647286  0.066064  0.088994  0.212326  0.516184  0.490260   
12  0.836990

In [7]:
# Входные данные для обучения модели (x) заменяем на те, которые имеют сильную корреляцию друг с другом (коэффициент корреляции больше 0.9).

correlation = 0.9

df = x[x.corr() > correlation].fillna(0)

# Данные x_test также преобразовываем, чтобы оставить только те, которые имеют максимальную корреляцию друг с другом (коэффициент корреляции больше 0.9).

df_test = x_test[x_test.corr() > correlation].fillna(0)

tree_clf = tree.DecisionTreeClassifier().fit(df, y)
y_pred = tree_clf.predict(df_test)

print(y_pred)

[1 1 0 1 1 1 1 1 0 1]


In [8]:
# Увеличиваем коэффициент корреляции до 0.95

correlation = 0.95

df = x[x.corr() > correlation].fillna(0)
df_test = x_test[x_test.corr() > correlation].fillna(0)

tree_clf = tree.DecisionTreeClassifier().fit(df, y)

y_pred = tree_clf.predict(df_test)

print(y_pred)

[1 1 0 1 1 1 0 1 0 1]
